apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.deployment.name }}-svc
  labels:
    app: {{ .Values.deployment.name }}-svc
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.container.containerPort }}
      targetPort: {{ .Values.container.containerPort }}
      {{- if eq .Values.service.type "NodePort" }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end}}
      protocol: TCP
  selector:
    app: {{ .Values.deployment.name }}