--- 

- shell: cd "{{ home }}/01-php-app" && docker build --network host -t n1t1n1g1r1/devops-mif_images:testing .
  register: output

- debug: var=output.stdout

- shell: docker push n1t1n1g1r1/devops-mif_images:testing

- shell: docker images
  # register: images

# - debug: var=images.stdout