deployment:
  name: mfix-app
  replicas: 2

service:
  # type: LoadBalancer
  type: NodePort
  nodePort: 30080

repository:
  name: n1t1n1g1r1/devops-mif_images
  tag: testing

container:
  protocol: TCP
  containerPort: 80

securityContext:
  runAsUser: 185
  runAsGroup: 185
  allowPrivilegeEscalation: false
  runAsNonRoot: true

livenessProbe:
  # httpGet:
  #   path: /health-check
  #   port: 80
  #   scheme: HTTP
  tcpSocker:
    port: 80
  initialDelaySeconds: 60
  timeoutSeconds: 60
  failureThreshold: 3

readinessProbe:
  failureThreshold: 3
  # httpGet:
  #   path: /health-check
  #   port: 80
  #   scheme: HTTP
  tcpSocker:
    port: 80
  initialDelaySeconds: 20
  periodSeconds: 10

resources:
  limits:
    memory: 512Mi
    cpu: "1"
  requests:
    memory: 256Mi
    cpu: "500m"

imagePullPolicy: IfNotPresent
imagePullSecrets:
  - name: mysecret